# Day 3 - NumPy Basics

### AI & ML Internship - Codomax Digital Solutions

**Name:** Mohammed Sanjidh

This notebook demonstrates the basic concepts of NumPy, including arrays, indexing, slicing, mathematical operations, and array calculations.

In [1]:
import numpy as np

print("NumPy imported successfully!")

ModuleNotFoundError: No module named 'numpy'

In [2]:
pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.6 MB 1.5 MB/s eta 0:00:08
   -- ------------------------------------- 0.8/12.6 MB 1.7 MB/s eta 0:00:07
   --- ------------------------------------ 1.0/12.6 MB 1.3 MB/s eta 0:00:10
   ---- ----------------------------------- 1.3/12.6 MB 1.2 MB/s eta 0:00:10
   ----- ---------------------------------- 1.8/12.6 MB 1.4 MB/s eta 0:00:08
   ------ --------------------------------- 2.1/12.6 MB 1.4 MB/s eta 0:00:08
   -------- ------------------------------- 2.6/12.6 MB 1.5 MB/s eta 0:00:07
   -------- ------------------------------- 2.6/12.6 MB 1.5 MB/s eta 0:00:07
   ---------- ----------------------------- 3.4/12.6 MB 1.6 MB/s eta 0:00:06
   ----------- ---------------------------- 3.7/12.6 MB 1.6 MB/s eta 0:00:06
   ------------ ----


[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


## Creating NumPy Arrays

In [5]:
import numpy as np

study_hours = np.array([1, 2, 3, 4, 5])

print(study_hours)
print(type(study_hours))

[1 2 3 4 5]
<class 'numpy.ndarray'>


## Array Indexing

In [6]:
study_hours = np.array([2, 4, 6, 8, 10])

print("First element:", study_hours[0])
print("Third element:", study_hours[2])
print("Last element:", study_hours[-1])

First element: 2
Third element: 6
Last element: 10


## Array Slicing

In [7]:
study_hours = np.array([1,2,3,4,5,6,7])

print(study_hours[1:5])
print(study_hours[:4])
print(study_hours[3:])

[2 3 4 5]
[1 2 3 4]
[4 5 6 7]


## Mathematical Operations

In [8]:
marks = np.array([60, 70, 80, 90, 100])

print("Original:", marks)

print("Add 5:", marks + 5)
print("Multiply by 2:", marks * 2)
print("Square:", marks ** 2)

Original: [ 60  70  80  90 100]
Add 5: [ 65  75  85  95 105]
Multiply by 2: [120 140 160 180 200]
Square: [ 3600  4900  6400  8100 10000]


## Array Statistics

In [9]:
marks = np.array([60,70,80,90,100])

print("Maximum:", np.max(marks))
print("Minimum:", np.min(marks))
print("Average:", np.mean(marks))
print("Sum:", np.sum(marks))

Maximum: 100
Minimum: 60
Average: 80.0
Sum: 400


## Mini Project - Student Study Hours Analysis

In [ ]:
import numpy as np

study_hours = np.array([2,4,5,6,8])

print("Study Hours:", study_hours)

print("Average Hours:", np.mean(study_hours))

print("Maximum Hours:", np.max(study_hours))

print("Minimum Hours:", np.min(study_hours))

improved_hours = study_hours + 1

print("After Improvement:", improved_hours)

Study Hours: [2 4 5 6 8]
Average Hours: 5.0
Maximum Hours: 8
Minimum Hours: 2
After Improvement: [3 5 6 7 9]
